package com.csj.cn.provider.mapper;

import com.csj.cn.common.dto.GoodsLike;
import com.csj.cn.common.dto.GoodsLikeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GoodsLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    long countByExample(GoodsLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int deleteByExample(GoodsLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int insert(GoodsLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int insertSelective(GoodsLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    List<GoodsLike> selectByExample(GoodsLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    GoodsLike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsLike record, @Param("example") GoodsLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsLike record, @Param("example") GoodsLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsLike record);

    /**
     * 删除表数据
     *
     * @return
     */
    int truncateTable();
}