package com.csj.cn.provider.mapper;

import com.csj.cn.common.dto.WxAndUser;
import com.csj.cn.common.dto.WxAndUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxAndUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    long countByExample(WxAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int deleteByExample(WxAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int insert(WxAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int insertSelective(WxAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    List<WxAndUser> selectByExample(WxAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    WxAndUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxAndUser record, @Param("example") WxAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxAndUser record, @Param("example") WxAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxAndUser record);
}