package com.csj.cn.common.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goods_like
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodsLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_like.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_like.good_id
     *
     * @mbg.generated
     */
    private String goodId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_like.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   点赞状态(0：取消点赞，1：点赞)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_like.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_like.id
     *
     * @return the value of goods_like.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_like.id
     *
     * @param id the value for goods_like.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_like.good_id
     *
     * @return the value of goods_like.good_id
     *
     * @mbg.generated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_like.good_id
     *
     * @param goodId the value for goods_like.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_like.user_id
     *
     * @return the value of goods_like.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_like.user_id
     *
     * @param userId the value for goods_like.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_like.status
     *
     * @return the value of goods_like.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_like.status
     *
     * @param status the value for goods_like.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}